Screen:

    MDRaisedButton:
        text: "Light Button"
        pos_hint: {"center_x":0.5, "center_y": 0.7}
        mg_bg_color: app.theme_cls.primary_light

    MDRaisedButton:
        text: "Second Button"
        pos_hint: {"center_x":0.5, "center_y": 0.5}
        

    MDRaisedButton:
        text: "Third Button"
        pos_hint: {"center_x":0.5, "center_y": 0.3}
        mg_bg_color: app.theme_cls.primary_dark

